// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectionStats(arg1:string):Promise<Record<string, any>>;

export function CreateCollection(arg1:string):Promise<void>;

export function CreateIndex(arg1:string,arg2:string):Promise<void>;

export function DeleteDocument(arg1:string,arg2:string):Promise<void>;

export function DropCollection(arg1:string):Promise<void>;

export function DropIndex(arg1:string,arg2:string):Promise<void>;

export function FindDocuments(arg1:string,arg2:Record<string, any>):Promise<Array<Record<string, any>>>;

export function FindDocumentsQuery(arg1:string,arg2:Record<string, any>):Promise<Array<Record<string, any>>>;

export function GetDocument(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetAPIKey():Promise<string>;

export function GetServerURL():Promise<string>;

export function InsertDocument(arg1:string,arg2:Record<string, any>):Promise<string>;

export function KVDelete(arg1:string):Promise<void>;

export function KVFlush():Promise<void>;

export function KVGet(arg1:string):Promise<string>;

export function KVIncr(arg1:string,arg2:number):Promise<number>;

export function KVKeys(arg1:string):Promise<Array<string>>;

export function KVSet(arg1:string,arg2:string,arg3:number):Promise<void>;

export function KVStats():Promise<Record<string, any>>;

export function ListCollections():Promise<Array<string>>;

export function ListIndexes(arg1:string):Promise<Array<string>>;

export function PingServer():Promise<void>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function UpdateDocument(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;
