// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectionStats(arg1) {
  return window['go']['main']['App']['CollectionStats'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateIndex(arg1, arg2) {
  return window['go']['main']['App']['CreateIndex'](arg1, arg2);
}

export function DeleteDocument(arg1, arg2) {
  return window['go']['main']['App']['DeleteDocument'](arg1, arg2);
}

export function DropCollection(arg1) {
  return window['go']['main']['App']['DropCollection'](arg1);
}

export function DropIndex(arg1, arg2) {
  return window['go']['main']['App']['DropIndex'](arg1, arg2);
}

export function FindDocuments(arg1, arg2) {
  return window['go']['main']['App']['FindDocuments'](arg1, arg2);
}

export function FindDocumentsQuery(arg1, arg2) {
  return window['go']['main']['App']['FindDocumentsQuery'](arg1, arg2);
}

export function GetDocument(arg1, arg2) {
  return window['go']['main']['App']['GetDocument'](arg1, arg2);
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function InsertDocument(arg1, arg2) {
  return window['go']['main']['App']['InsertDocument'](arg1, arg2);
}

export function KVDelete(arg1) {
  return window['go']['main']['App']['KVDelete'](arg1);
}

export function KVFlush() {
  return window['go']['main']['App']['KVFlush']();
}

export function KVGet(arg1) {
  return window['go']['main']['App']['KVGet'](arg1);
}

export function KVIncr(arg1, arg2) {
  return window['go']['main']['App']['KVIncr'](arg1, arg2);
}

export function KVKeys(arg1) {
  return window['go']['main']['App']['KVKeys'](arg1);
}

export function KVSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['KVSet'](arg1, arg2, arg3);
}

export function KVStats() {
  return window['go']['main']['App']['KVStats']();
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListIndexes(arg1) {
  return window['go']['main']['App']['ListIndexes'](arg1);
}

export function PingServer() {
  return window['go']['main']['App']['PingServer']();
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function UpdateDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDocument'](arg1, arg2, arg3);
}
